#version: '3.8'
#
#services:
#  
#  # Configuración de Zookeeper para Kafka
#  zookeeper:
#    image: bitnami/zookeeper:latest
#    environment:
#      - ZOO_ENABLE_AUTH=no
#      - ALLOW_ANONYMOUS_LOGIN=yes
#      - ZOOKEEPER_CLIENT_PORT=2181
#    networks:
#      - distributed_net
#
#  # Kafka para mensajería
#  kafka:
#    image: bitnami/kafka:latest
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092  # Cambia 'localhost' si usas otra IP
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    depends_on:
#      - zookeeper
#    networks:
#      - distributed_net
#    ports:
#      - "9092:9092"
#
#  # Apache Spark para procesamiento en tiempo real
#  spark:
#    image: bitnami/spark:latest
#    environment:
#      - SPARK_MODE=master
#      - ALLOW_ANONYMOUS_LOGIN=yes
#    depends_on:
#      - kafka
#    networks:
#      - distributed_net
#    ports:
#      - "8080:8080"
#
#  # Apache Cassandra para almacenamiento de datos históricos
#  cassandra:
#    image: cassandra:latest
#    environment:
#      - CASSANDRA_CLUSTER_NAME=waze_cluster
#      - CASSANDRA_SEEDS=cassandra
#    ports:
#      - "9042:9042"
#    networks:
#      - distributed_net
#
#  # Elasticsearch para búsqueda en tiempo real
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
#    environment:
#      - discovery.type=single-node
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    networks:
#      - distributed_net
#
#  # Kibana para visualización
#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.10.1
#    ports:
#      - "5601:5601"
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    depends_on:
#      - elasticsearch
#    networks:
#      - distributed_net
#
#networks:
#  distributed_net:
#    driver: bridge


version: '3.8'

services:
  
  # Configuración de Zookeeper para Kafka
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ZOO_ENABLE_AUTH=no
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - distributed_net

  # Kafka para mensajería
  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - distributed_net
    ports:
      - "9092:9092"

  # Apache Spark Master
  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - distributed_net
    ports:
      - "8080:8080"

  # Apache Spark Worker
  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - ALLOW_ANONYMOUS_LOGIN=yes
    depends_on:
      - spark-master
    networks:
      - distributed_net

  # Apache Cassandra para almacenamiento de datos históricos
  cassandra:
    image: cassandra:latest
    environment:
      - CASSANDRA_CLUSTER_NAME=waze_cluster
      - CASSANDRA_SEEDS=cassandra
    ports:
      - "9042:9042"
    networks:
      - distributed_net

  # Elasticsearch para búsqueda en tiempo real
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.24
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - distributed_net

  # Kibana para visualización
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.5
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - distributed_net

networks:
  distributed_net:
    driver: bridge

